from typing import List

from pydantic import BaseModel


class EndpointDetail(BaseModel):
    """
    Details about an individual endpoint, including its name, path, description, and any parameters it requires.
    """

    name: str
    path: str
    description: str
    method: str
    parameters: List[str]


class APIDocumentationResponse(BaseModel):
    """
    The structure encapsulating the API documentation, detailing available endpoints, their functionalities, and how to use them.
    """

    version: str
    endpoints: List[EndpointDetail]


def api_documentation() -> APIDocumentationResponse:
    """
    Provides documentation for the available API endpoints and their usage.

    Returns:
    APIDocumentationResponse: The structure encapsulating the API documentation, detailing available endpoints, their functionalities, and how to use them.
    """
    endpoints = [
        EndpointDetail(
            name="Create QR Code",
            path="/create",
            description="Generates a QR code based on given data and customization options.",
            method="POST",
            parameters=[
                "data",
                "dataType",
                "size",
                "color",
                "logo",
                "errorCorrection",
                "format",
            ],
        ),
        EndpointDetail(
            name="Retrieve QR Code",
            path="/retrieve/{id}",
            description="Retrieves a previously generated QR code using its unique identifier.",
            method="GET",
            parameters=["id"],
        ),
        EndpointDetail(
            name="Update QR Code Preferences",
            path="/update/{id}",
            description="Updates the customization options for a previously generated QR code.",
            method="PATCH",
            parameters=["id", "size", "color", "logo"],
        ),
        EndpointDetail(
            name="Delete QR Code",
            path="/delete/{id}",
            description="Deletes a previously generated QR code.",
            method="DELETE",
            parameters=["id"],
        ),
        EndpointDetail(
            name="List QR Codes",
            path="/list",
            description="Lists all QR codes generated by a user.",
            method="GET",
            parameters=["userId"],
        ),
    ]
    api_documentation_response = APIDocumentationResponse(
        version="1.0", endpoints=endpoints
    )
    return api_documentation_response
